name: "Joseph Joel, MSc"
email: "josephjoel3099@gmail.com"
phone: "+44 7767952880"
location: "Glasgow, United Kingdom"
skills:
  - Python
  - ROS
  - SolidWorks
  - Simulink
  - MATLAB
  - C++
  - Altium
  - EasyEDA
  - Fusion 360
projects:
  - "jackal_robot"
  - "multi_robot_system"
  - "faby_telepresence"
